// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using fraud_rule_engine_service.Persistence;

#nullable disable

namespace fraud_rule_engine_service.Persistence.Migrations
{
    [DbContext(typeof(ApplicationReadWriteContext))]
    [Migration("20260923141852_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("fraud_rule_engine")
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("fraud_rule_engine_service.Persistence.Entities.FraudCaseEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("account_id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("text")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("currency");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("customer_id");

                    b.Property<DateTimeOffset>("EvaluatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("evaluated_at");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<int>("OverallScore")
                        .HasColumnType("integer")
                        .HasColumnName("overall_score");

                    b.Property<int>("Severity")
                        .HasColumnType("integer")
                        .HasColumnName("severity");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("transaction_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_fraud_cases");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_fraud_cases_customer_id");

                    b.HasIndex("Severity")
                        .HasDatabaseName("ix_fraud_cases_severity");

                    b.HasIndex("TransactionId")
                        .HasDatabaseName("ix_fraud_cases_transaction_id");

                    b.HasIndex("AccountId", "EvaluatedAt")
                        .HasDatabaseName("ix_fraud_cases_account_id_evaluated_at");

                    b.ToTable("fraud_cases", "fraud_rule_engine");
                });

            modelBuilder.Entity("fraud_rule_engine_service.Persistence.Entities.FraudCaseTriggeredRuleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("FraudCaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("fraud_case_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<string>("RuleCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rule_code");

                    b.Property<string>("RuleName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rule_name");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.HasKey("Id")
                        .HasName("pk_fraud_case_triggered_rules");

                    b.HasIndex("FraudCaseId")
                        .HasDatabaseName("ix_fraud_case_triggered_rules_fraud_case_id");

                    b.HasIndex("RuleCode")
                        .HasDatabaseName("ix_fraud_case_triggered_rules_rule_code");

                    b.ToTable("fraud_case_triggered_rules", "fraud_rule_engine");
                });

            modelBuilder.Entity("fraud_rule_engine_service.Persistence.Entities.TransactionSnapshotEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("account_id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<int>("Channel")
                        .HasColumnType("integer")
                        .HasColumnName("channel");

                    b.Property<string>("CounterpartyAccountId")
                        .HasColumnType("text")
                        .HasColumnName("counterparty_account_id");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("country_code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("currency");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("customer_id");

                    b.Property<string>("DeviceId")
                        .HasColumnType("text")
                        .HasColumnName("device_id");

                    b.Property<bool>("IsNewPayee")
                        .HasColumnType("boolean")
                        .HasColumnName("is_new_payee");

                    b.Property<string>("MerchantCategoryCode")
                        .HasColumnType("text")
                        .HasColumnName("merchant_category_code");

                    b.Property<string>("MerchantName")
                        .HasColumnType("text")
                        .HasColumnName("merchant_name");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("transaction_id");

                    b.HasKey("Id")
                        .HasName("pk_transaction_snapshots");

                    b.HasIndex("TransactionId")
                        .IsUnique()
                        .HasDatabaseName("ix_transaction_snapshots_transaction_id");

                    b.HasIndex("AccountId", "OccurredAt")
                        .HasDatabaseName("ix_transaction_snapshots_account_id_occurred_at");

                    b.ToTable("transaction_snapshots", "fraud_rule_engine");
                });

            modelBuilder.Entity("fraud_rule_engine_service.Persistence.Entities.FraudCaseTriggeredRuleEntity", b =>
                {
                    b.HasOne("fraud_rule_engine_service.Persistence.Entities.FraudCaseEntity", "FraudCase")
                        .WithMany("TriggeredRules")
                        .HasForeignKey("FraudCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_fraud_case_triggered_rules_fraud_cases_fraud_case_id");

                    b.Navigation("FraudCase");
                });

            modelBuilder.Entity("fraud_rule_engine_service.Persistence.Entities.FraudCaseEntity", b =>
                {
                    b.Navigation("TriggeredRules");
                });
#pragma warning restore 612, 618
        }
    }
}
